{{- if .Values.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "harvis-ai.fullname" . }}-pgsql-pvc
  labels:
    {{- include "harvis-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
  {{- if .Values.postgresql.persistence.storageClass }}
  {{- if (eq "-" .Values.postgresql.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass }}
  {{- end }}
  {{- end }}
---
{{- end }}
{{- if .Values.n8n.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "harvis-ai.fullname" . }}-n8n-pvc
  labels:
    {{- include "harvis-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: n8n
spec:
  accessModes:
    - {{ .Values.n8n.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.n8n.persistence.size }}
  {{- if .Values.n8n.persistence.storageClass }}
  {{- if (eq "-" .Values.n8n.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.n8n.persistence.storageClass }}
  {{- end }}
  {{- end }}
---
{{- end }}
{{- if .Values.backend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "harvis-ai.fullname" . }}-backend-pvc
  labels:
    {{- include "harvis-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
  {{- if .Values.backend.persistence.storageClass }}
  {{- if (eq "-" .Values.backend.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  {{- end }}
  {{- end }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-model-cache
  labels:
    {{- include "harvis-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  {{- if .Values.global.storageClass }}
  {{- if (eq "-" .Values.global.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "harvis-ai.fullname" . }}-embedding-pvc
  labels:
    {{- include "harvis-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  {{- if .Values.global.storageClass }}
  {{- if (eq "-" .Values.global.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  {{- end }}