---
# ServiceAccount for GitLab Runner
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
  labels:
    app.kubernetes.io/name: gitlab-runner
    app.kubernetes.io/component: ci-cd

---
# ClusterRole for GitLab Runner (needed for K8s executor)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab-runner
  labels:
    app.kubernetes.io/name: gitlab-runner
    app.kubernetes.io/component: ci-cd
rules:
  # Access to pods (for builds)
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

  # Access to pod attachments (for exec and logs)
  - apiGroups: [""]
    resources: ["pods/attach"]
    verbs: ["get", "create"]

  # Access to secrets (for build credentials)
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update"]

  # Access to configmaps
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]

  # Access to services
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]

  # Access to persistent volume claims
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "create", "delete"]

---
# ClusterRoleBinding for GitLab Runner
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab-runner
  labels:
    app.kubernetes.io/name: gitlab-runner
    app.kubernetes.io/component: ci-cd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab-runner
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: gitlab-runner

---
# Role for GitLab Runner in its own namespace (full access)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
  labels:
    app.kubernetes.io/name: gitlab-runner
    app.kubernetes.io/component: ci-cd
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
# RoleBinding for GitLab Runner in its own namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
  labels:
    app.kubernetes.io/name: gitlab-runner
    app.kubernetes.io/component: ci-cd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-runner
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: gitlab-runner
