---
# Local StorageClass for node-specific storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-node-storage
  labels:
    app.kubernetes.io/name: harvis-ai
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
# Local PersistentVolume for ML Models on Node1 (pop-os with RTX 4090)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ml-models-node1-pv
  labels:
    app.kubernetes.io/name: harvis-ai
    app.kubernetes.io/component: ml-models
    node: pop-os
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-node-storage
  local:
    path: /mnt/ml-models-cache  # Local directory on node1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pop-os  # Pin to node1
---
# Local PersistentVolumeClaim for ML Models (Node1)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-models-node1-pvc
  namespace: ai-agents
  labels:
    app.kubernetes.io/name: harvis-ai
    app.kubernetes.io/component: ml-models
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-node-storage
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      node: pop-os
---
# Local PersistentVolume for Ollama Models on Node2 (pop-os-343570d8 with RTX 3090 Ti)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-models-node2-pv
  labels:
    app.kubernetes.io/name: harvis-ai
    app.kubernetes.io/component: ollama-models
    node: pop-os-343570d8
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-node-storage
  local:
    path: /mnt/ollama-models  # Local directory on node2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pop-os-343570d8  # Pin to node2
---
# Local PersistentVolumeClaim for Ollama Models (Node2)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-node2-pvc
  namespace: ai-agents
  labels:
    app.kubernetes.io/name: harvis-ai
    app.kubernetes.io/component: ollama-models
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-node-storage
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      node: pop-os-343570d8
