---
# Local PVC for ML Models (will be created on node1/pop-os because backend pod has nodeSelector)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-models-local-pvc
  namespace: ai-agents
  labels:
    app.kubernetes.io/name: harvis-ai
    app.kubernetes.io/component: ml-models
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  # K3s default dynamic provisioner
  resources:
    requests:
      storage: 50Gi
---
# Local PVC for Ollama Models (will be created on node2/pop-os-343570d8 because ollama pod has nodeSelector)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models-local-pvc
  namespace: ai-agents
  labels:
    app.kubernetes.io/name: harvis-ai
    app.kubernetes.io/component: ollama-models
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  # K3s default dynamic provisioner
  resources:
    requests:
      storage: 100Gi
