apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvis-ai-ollama
  namespace: ai-agents
  labels:
    app.kubernetes.io/name: harvis-ai
    app.kubernetes.io/component: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: harvis-ai
      app.kubernetes.io/component: ollama
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harvis-ai
        app.kubernetes.io/component: ollama
    spec:
      runtimeClassName: nvidia
      # Node affinity: Force scheduling on Node 2 (pop-os-343570d8) for Ollama workload
      nodeSelector:
        kubernetes.io/hostname: pop-os-343570d8
      containers:
        - name: ollama
          image: "ollama/ollama:latest"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              nvidia.com/gpu: 1  # Full GPU for Ollama
            requests:
              memory: 12Gi
              cpu: 2000m
          ports:
            - name: ollama
              containerPort: 11434
              protocol: TCP
          volumeMounts:
            - name: ollama-models
              mountPath: /root/.ollama
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -ex
              # Start Ollama server only - models can be pulled via API after startup
              ollama serve
          livenessProbe:
            httpGet:
              path: /api/tags
              port: 11434
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/tags
              port: 11434
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5

      volumes:
        - name: ollama-models
          persistentVolumeClaim:
            claimName: ollama-models-local-pvc  # Local storage on node2 for fast model loading (mmap support)
---
apiVersion: v1
kind: Service
metadata:
  name: harvis-ai-ollama
  namespace: ai-agents
  labels:
    app.kubernetes.io/name: harvis-ai
    app.kubernetes.io/component: ollama
spec:
  type: ClusterIP
  ports:
    - name: ollama
      port: 11434
      targetPort: ollama
      protocol: TCP
  selector:
    app.kubernetes.io/name: harvis-ai
    app.kubernetes.io/component: ollama
